/**
 * Line-art dog assets (transparent PNG) for specific breeds — replaces photo sprites from the sheet.
 * Generated by: node scripts/split-line-art-doodles.mjs
 *
 * Line-art crops: `cavoodleLineArtCrop.ts`, `cavalierLineArtCrop.ts` (not `commonSpriteCrops.ts` for those breeds).
 */
import { cavalierLineArtCrop, cavalierLineArtSheetSize } from "@/constants/cavalierLineArtCrop";
import { cavoodleLineArtCrop } from "@/constants/cavoodleLineArtCrop";

export const LINE_ART_SPRITE_SIZE = { w: 256, h: 682 } as const;

/** Baseline Y in sprite pixels (near bottom of standing dog). */
const FEET_Y = 648;

export type LineArtSpriteEntry = {
  source: number;
  /** PNG size when not the default `LINE_ART_SPRITE_SIZE` template. */
  sheet?: { w: number; h: number };
  crop: {
    x: number;
    y: number;
    w: number;
    h: number;
    feetY: number;
    dx?: number;
    dy?: number;
    scale?: number;
  };
};

const groodle = require("../../assets/breed-line-art/groodle.png");
const labradoodle = require("../../assets/breed-line-art/labradoodle.png");
const cavoodle = require("../../assets/breed-line-art/cavoodle.png");
const cavalier = require("../../assets/breed-line-art/cavalier-king-charles-spaniel.png");

const fullCrop = {
  x: 0,
  y: 0,
  w: LINE_ART_SPRITE_SIZE.w,
  h: LINE_ART_SPRITE_SIZE.h,
  feetY: FEET_Y,
};

export const breedLineArtById: Record<string, LineArtSpriteEntry> = {
  groodle: { source: groodle, crop: { ...fullCrop } },
  labradoodle: { source: labradoodle, crop: { ...fullCrop } },
  cavoodle: { source: cavoodle, crop: { ...cavoodleLineArtCrop } },
  "cavalier-king-charles-spaniel": {
    source: cavalier,
    sheet: { ...cavalierLineArtSheetSize },
    crop: { ...cavalierLineArtCrop },
  },
};

/** Sheet dimensions for layout math (must match the PNG file for this entry). */
export function getLineArtSheetSize(entry: LineArtSpriteEntry): { w: number; h: number } {
  return entry.sheet ?? LINE_ART_SPRITE_SIZE;
}

export function getBreedLineArt(breedId: string): LineArtSpriteEntry | null {
  return breedLineArtById[breedId] ?? null;
}
