import type { Breed, BreedRarity } from "@/types/app";

/** Base points per scan by rarity (featured multiplier applied in the store). */
export const RARITY_POINTS: Record<BreedRarity, number> = {
  common: 1,
  uncommon: 3,
  rare: 7,
  legendary: 15,
};

export const breedsCatalog: Breed[] = [
  {
    id: "cavoodle",
    name: "Cavoodle",
    rarity: "common",
    points: RARITY_POINTS.common,
    subtitle: "Affectionate companion dog with a playful and social nature.",
    description:
      "Cavoodles combine the gentle temperament of the Cavalier King Charles Spaniel with the intelligence of the Poodle. They are adaptable family dogs that thrive on companionship and enjoy both playtime and cuddles.",
    origin: "Australia",
    temperament: "Friendly, Intelligent, Affectionate",
    size: "Small",
    lifespan: "12–15 years",
    referencePhotoUrl: null,
  },
  {
    id: "labrador-retriever",
    name: "Labrador Retriever",
    rarity: "common",
    points: RARITY_POINTS.common,
    subtitle: "Loyal and outgoing sporting dog known for its friendly personality.",
    description:
      "Labradors are highly social dogs originally bred for retrieving game and fishing nets. They are intelligent, eager to please, and make excellent family companions.",
    origin: "Canada",
    temperament: "Friendly, Energetic, Loyal",
    size: "Large",
    lifespan: "10–14 years",
    referencePhotoUrl: null,
  },
  {
    id: "golden-retriever",
    name: "Golden Retriever",
    rarity: "common",
    points: RARITY_POINTS.common,
    subtitle: "Gentle and intelligent retriever famous for its loving temperament.",
    description:
      "Golden Retrievers are dependable family dogs with a calm and affectionate personality. They love outdoor activities, swimming, and spending time with people.",
    origin: "Scotland",
    temperament: "Friendly, Patient, Intelligent",
    size: "Large",
    lifespan: "10–12 years",
    referencePhotoUrl: null,
  },
  {
    id: "french-bulldog",
    name: "French Bulldog",
    rarity: "common",
    points: RARITY_POINTS.common,
    subtitle: "Compact companion dog with a charming and playful personality.",
    description:
      "French Bulldogs are relaxed indoor companions that enjoy human interaction and short bursts of play. Their expressive faces and bat-like ears make them instantly recognisable.",
    origin: "France",
    temperament: "Playful, Adaptable, Affectionate",
    size: "Small",
    lifespan: "10–12 years",
    referencePhotoUrl: null,
  },
  {
    id: "german-shepherd",
    name: "German Shepherd",
    rarity: "common",
    points: RARITY_POINTS.common,
    subtitle: "Confident working dog known for intelligence and loyalty.",
    description:
      "German Shepherds are versatile working dogs commonly used in police, military, and rescue roles. They are protective, highly trainable, and thrive with structure and activity.",
    origin: "Germany",
    temperament: "Loyal, Courageous, Intelligent",
    size: "Large",
    lifespan: "9–13 years",
    referencePhotoUrl: null,
  },
  {
    id: "border-collie",
    name: "Border Collie",
    rarity: "common",
    points: RARITY_POINTS.common,
    subtitle: "Exceptionally intelligent herding dog built for speed and focus.",
    description:
      "Border Collies are highly intelligent working dogs that excel in agility, obedience, and problem solving. They require lots of mental stimulation and physical exercise.",
    origin: "United Kingdom",
    temperament: "Energetic, Focused, Responsive",
    size: "Medium",
    lifespan: "12–15 years",
    referencePhotoUrl: null,
  },
  {
    id: "staffordshire-bull-terrier",
    name: "Staffordshire Bull Terrier",
    rarity: "common",
    points: RARITY_POINTS.common,
    subtitle: "Strong and affectionate companion with a people-loving personality.",
    description:
      "Staffies are muscular and confident dogs that are deeply loyal to their families. Despite their tough appearance, they are often gentle and playful companions.",
    origin: "England",
    temperament: "Brave, Affectionate, Energetic",
    size: "Medium",
    lifespan: "12–14 years",
    referencePhotoUrl: null,
  },
  {
    id: "groodle",
    name: "Groodle",
    rarity: "common",
    points: RARITY_POINTS.common,
    subtitle: "Friendly and intelligent crossbreed loved for its fluffy coat.",
    description:
      "Groodles combine the intelligence of the Poodle with the friendliness of the Golden Retriever. They are popular family dogs that enjoy activity and companionship.",
    origin: "Australia",
    temperament: "Social, Intelligent, Gentle",
    size: "Large",
    lifespan: "10–15 years",
    referencePhotoUrl: null,
  },
  {
    id: "miniature-dachshund",
    name: "Miniature Dachshund",
    rarity: "common",
    points: RARITY_POINTS.common,
    subtitle: "Curious and courageous small dog with a distinctive long body.",
    description:
      "Miniature Dachshunds were originally bred to hunt badgers underground. They are lively little dogs with big personalities and strong loyalty to their owners.",
    origin: "Germany",
    temperament: "Bold, Curious, Clever",
    size: "Small",
    lifespan: "12–16 years",
    referencePhotoUrl: null,
  },
  {
    id: "cavalier-king-charles-spaniel",
    name: "Cavalier King Charles Spaniel",
    rarity: "common",
    points: RARITY_POINTS.common,
    subtitle: "Elegant toy spaniel known for its affectionate temperament.",
    description:
      "Cavaliers are loving companion dogs that enjoy cuddling and human attention. They are adaptable pets suited to both active and relaxed households.",
    origin: "United Kingdom",
    temperament: "Gentle, Affectionate, Adaptable",
    size: "Small",
    lifespan: "10–14 years",
    referencePhotoUrl: null,
  },
  {
    id: "labradoodle",
    name: "Labradoodle",
    rarity: "common",
    points: RARITY_POINTS.common,
    subtitle: "Friendly hybrid breed prized for intelligence and low shedding coats.",
    description:
      "Labradoodles combine Labrador friendliness with Poodle intelligence. They are energetic family dogs that enjoy activity and close companionship.",
    origin: "Australia",
    temperament: "Outgoing, Intelligent, Social",
    size: "Medium–Large",
    lifespan: "12–14 years",
    referencePhotoUrl: null,
  },
  {
    id: "poodle-miniature",
    name: "Poodle (Miniature)",
    rarity: "common",
    points: RARITY_POINTS.common,
    subtitle: "Elegant and highly intelligent companion with a lively personality.",
    description:
      "Miniature Poodles are energetic dogs with excellent trainability and low-shedding coats. They thrive on mental stimulation and human interaction.",
    origin: "France",
    temperament: "Smart, Alert, Active",
    size: "Small",
    lifespan: "12–15 years",
    referencePhotoUrl: null,
  },
  {
    id: "maltese",
    name: "Maltese",
    rarity: "common",
    points: RARITY_POINTS.common,
    subtitle: "Tiny companion dog with a graceful appearance and loving personality.",
    description:
      "Maltese dogs are known for their silky white coats and friendly temperament. They are adaptable indoor companions that bond closely with their owners.",
    origin: "Malta",
    temperament: "Affectionate, Gentle, Playful",
    size: "Small",
    lifespan: "12–15 years",
    referencePhotoUrl: null,
  },
  {
    id: "jack-russell-terrier",
    name: "Jack Russell Terrier",
    rarity: "common",
    points: RARITY_POINTS.common,
    subtitle: "Fearless and energetic terrier packed with personality.",
    description:
      "Jack Russells are lively dogs bred for fox hunting and outdoor work. They are athletic, intelligent, and require lots of activity to stay happy.",
    origin: "England",
    temperament: "Energetic, Clever, Bold",
    size: "Small",
    lifespan: "13–16 years",
    referencePhotoUrl: null,
  },
  {
    id: "shih-tzu",
    name: "Shih Tzu",
    rarity: "common",
    points: RARITY_POINTS.common,
    subtitle: "Charming lap dog bred for companionship and affection.",
    description:
      "Shih Tzus were originally bred as royal companion dogs in China. They are affectionate pets that enjoy attention and relaxed indoor living.",
    origin: "China",
    temperament: "Affectionate, Friendly, Outgoing",
    size: "Small",
    lifespan: "10–16 years",
    referencePhotoUrl: null,
  },
  {
    id: "cocker-spaniel",
    name: "Cocker Spaniel",
    rarity: "uncommon",
    points: RARITY_POINTS.uncommon,
    subtitle: "Gentle sporting dog known for its affectionate and cheerful personality.",
    description:
      "Cocker Spaniels are friendly companion dogs originally bred for bird hunting. They are energetic, loving, and thrive in active households with lots of attention.",
    origin: "United Kingdom",
    temperament: "Affectionate, Gentle, Playful",
    size: "Medium",
    lifespan: "12–15 years",
    referencePhotoUrl: null,
  },
  {
    id: "beagle",
    name: "Beagle",
    rarity: "uncommon",
    points: RARITY_POINTS.uncommon,
    subtitle: "Curious scent hound with a happy and adventurous spirit.",
    description:
      "Beagles are scent hounds bred for tracking rabbits and small game. They are social, vocal, and love exploring with their powerful sense of smell.",
    origin: "England",
    temperament: "Curious, Friendly, Energetic",
    size: "Medium",
    lifespan: "12–15 years",
    referencePhotoUrl: null,
  },
  {
    id: "miniature-schnauzer",
    name: "Miniature Schnauzer",
    rarity: "uncommon",
    points: RARITY_POINTS.uncommon,
    subtitle: "Alert and spirited companion with a distinctive beard and eyebrows.",
    description:
      "Miniature Schnauzers are energetic little dogs known for their intelligence and bold personality. They make excellent watchdogs and enjoy being part of family life.",
    origin: "Germany",
    temperament: "Alert, Intelligent, Friendly",
    size: "Small",
    lifespan: "12–15 years",
    referencePhotoUrl: null,
  },
  {
    id: "spoodle",
    name: "Spoodle",
    rarity: "uncommon",
    points: RARITY_POINTS.uncommon,
    subtitle: "Friendly and affectionate crossbreed with a playful personality.",
    description:
      "Spoodles combine the affectionate nature of the Cocker Spaniel with the intelligence of the Poodle. They are adaptable family dogs that enjoy companionship and play.",
    origin: "Australia",
    temperament: "Social, Gentle, Intelligent",
    size: "Small–Medium",
    lifespan: "12–15 years",
    referencePhotoUrl: null,
  },
  {
    id: "australian-shepherd",
    name: "Australian Shepherd",
    rarity: "uncommon",
    points: RARITY_POINTS.uncommon,
    subtitle: "Highly intelligent herding dog built for activity and agility.",
    description:
      "Australian Shepherds are athletic working dogs that excel in agility, obedience, and herding. They thrive with active owners and lots of mental stimulation.",
    origin: "United States",
    temperament: "Energetic, Loyal, Intelligent",
    size: "Medium",
    lifespan: "12–15 years",
    referencePhotoUrl: null,
  },
  {
    id: "pug",
    name: "Pug",
    rarity: "uncommon",
    points: RARITY_POINTS.uncommon,
    subtitle: "Compact companion dog with a charming and mischievous personality.",
    description:
      "Pugs are social companion dogs known for their wrinkled faces and expressive personalities. They enjoy human company and adapt well to apartment living.",
    origin: "China",
    temperament: "Affectionate, Playful, Charming",
    size: "Small",
    lifespan: "12–15 years",
    referencePhotoUrl: null,
  },
  {
    id: "chihuahua",
    name: "Chihuahua",
    rarity: "uncommon",
    points: RARITY_POINTS.uncommon,
    subtitle: "Tiny but confident companion packed with personality.",
    description:
      "Chihuahuas are one of the world’s smallest dog breeds but often act much larger than their size suggests. They bond closely with owners and are highly alert.",
    origin: "Mexico",
    temperament: "Bold, Alert, Loyal",
    size: "Tiny",
    lifespan: "14–17 years",
    referencePhotoUrl: null,
  },
  {
    id: "bichon-frise",
    name: "Bichon Frise",
    rarity: "uncommon",
    points: RARITY_POINTS.uncommon,
    subtitle: "Cheerful fluffy companion dog with a lively personality.",
    description:
      "Bichon Frises are social companion dogs with soft curly coats and outgoing personalities. They enjoy attention and are known for their happy temperament.",
    origin: "France",
    temperament: "Playful, Friendly, Affectionate",
    size: "Small",
    lifespan: "12–15 years",
    referencePhotoUrl: null,
  },
  {
    id: "boxer",
    name: "Boxer",
    rarity: "uncommon",
    points: RARITY_POINTS.uncommon,
    subtitle: "Athletic and loyal working dog with endless enthusiasm.",
    description:
      "Boxers are muscular working dogs known for their playful personalities and strong bonds with families. They are energetic companions that love activity and attention.",
    origin: "Germany",
    temperament: "Energetic, Loyal, Playful",
    size: "Large",
    lifespan: "10–12 years",
    referencePhotoUrl: null,
  },
  {
    id: "rottweiler",
    name: "Rottweiler",
    rarity: "uncommon",
    points: RARITY_POINTS.uncommon,
    subtitle: "Powerful guardian dog known for loyalty and confidence.",
    description:
      "Rottweilers are strong working dogs originally used for herding and guarding livestock. They are calm, intelligent, and deeply devoted to their families.",
    origin: "Germany",
    temperament: "Confident, Loyal, Protective",
    size: "Large",
    lifespan: "8–10 years",
    referencePhotoUrl: null,
  },
  {
    id: "siberian-husky",
    name: "Siberian Husky",
    rarity: "uncommon",
    points: RARITY_POINTS.uncommon,
    subtitle: "Energetic sled dog famous for endurance and striking appearance.",
    description:
      "Siberian Huskies are athletic working dogs bred for pulling sleds across long distances. They are social pack dogs that love exercise and adventure.",
    origin: "Russia",
    temperament: "Energetic, Friendly, Independent",
    size: "Medium",
    lifespan: "12–14 years",
    referencePhotoUrl: null,
  },
  {
    id: "whippet",
    name: "Whippet",
    rarity: "uncommon",
    points: RARITY_POINTS.uncommon,
    subtitle: "Elegant and athletic sighthound built for speed.",
    description:
      "Whippets are sleek dogs bred for racing and chasing prey. They are surprisingly calm indoors and enjoy lounging when not running.",
    origin: "England",
    temperament: "Gentle, Quiet, Athletic",
    size: "Medium",
    lifespan: "12–15 years",
    referencePhotoUrl: null,
  },
  {
    id: "west-highland-white-terrier",
    name: "West Highland White Terrier",
    rarity: "uncommon",
    points: RARITY_POINTS.uncommon,
    subtitle: "Confident little terrier with a bright white coat and lively attitude.",
    description:
      "Westies are energetic terriers known for their independence and cheerful personality. They are sturdy little dogs that enjoy play and exploration.",
    origin: "Scotland",
    temperament: "Bold, Friendly, Alert",
    size: "Small",
    lifespan: "13–15 years",
    referencePhotoUrl: null,
  },
  {
    id: "australian-cattle-dog",
    name: "Australian Cattle Dog",
    rarity: "uncommon",
    points: RARITY_POINTS.uncommon,
    subtitle: "Hardworking herding dog built for stamina and intelligence.",
    description:
      "Australian Cattle Dogs are highly driven working dogs bred to herd livestock across long distances. They are intelligent, resilient, and thrive with active owners.",
    origin: "Australia",
    temperament: "Loyal, Energetic, Alert",
    size: "Medium",
    lifespan: "12–16 years",
    referencePhotoUrl: null,
  },
  {
    id: "kelpie",
    name: "Kelpie",
    rarity: "uncommon",
    points: RARITY_POINTS.uncommon,
    subtitle: "Agile Australian herding dog with incredible endurance.",
    description:
      "Kelpies are highly athletic working dogs bred for herding sheep across harsh Australian terrain. They excel in agility and require lots of physical and mental activity.",
    origin: "Australia",
    temperament: "Energetic, Intelligent, Alert",
    size: "Medium",
    lifespan: "12–15 years",
    referencePhotoUrl: null,
  },
  {
    id: "dalmatian",
    name: "Dalmatian",
    rarity: "uncommon",
    points: RARITY_POINTS.uncommon,
    subtitle: "Distinctive spotted dog known for endurance and elegance.",
    description:
      "Dalmatians are athletic dogs historically used as carriage dogs and firehouse mascots. They are energetic companions that enjoy exercise and adventure.",
    origin: "Croatia",
    temperament: "Energetic, Loyal, Outgoing",
    size: "Large",
    lifespan: "11–13 years",
    referencePhotoUrl: null,
  },
  {
    id: "shiba-inu",
    name: "Shiba Inu",
    rarity: "uncommon",
    points: RARITY_POINTS.uncommon,
    subtitle: "Independent and fox-like companion with a confident personality.",
    description:
      "Shiba Inus are agile Japanese hunting dogs known for their cat-like cleanliness and spirited personality. They are intelligent but often stubborn.",
    origin: "Japan",
    temperament: "Alert, Independent, Bold",
    size: "Small–Medium",
    lifespan: "12–15 years",
    referencePhotoUrl: null,
  },
  {
    id: "pomeranian",
    name: "Pomeranian",
    rarity: "uncommon",
    points: RARITY_POINTS.uncommon,
    subtitle: "Tiny fluffy companion with a huge personality.",
    description:
      "Pomeranians are energetic toy dogs with thick fluffy coats and confident attitudes. Despite their small size, they are alert and expressive companions.",
    origin: "Germany / Poland",
    temperament: "Bold, Lively, Intelligent",
    size: "Tiny",
    lifespan: "12–16 years",
    referencePhotoUrl: null,
  },
  {
    id: "yorkshire-terrier",
    name: "Yorkshire Terrier",
    rarity: "uncommon",
    points: RARITY_POINTS.uncommon,
    subtitle: "Tiny terrier with a confident attitude and silky coat.",
    description:
      "Yorkshire Terriers were originally bred to catch rats in textile mills. They are spirited little dogs that bond closely with their owners.",
    origin: "England",
    temperament: "Bold, Affectionate, Energetic",
    size: "Tiny",
    lifespan: "13–16 years",
    referencePhotoUrl: null,
  },
  {
    id: "bull-terrier",
    name: "Bull Terrier",
    rarity: "uncommon",
    points: RARITY_POINTS.uncommon,
    subtitle: "Strong and playful companion recognised by its unique egg-shaped head.",
    description:
      "Bull Terriers are muscular dogs known for their clownish personalities and loyalty. They are energetic companions that enjoy play and human interaction.",
    origin: "England",
    temperament: "Playful, Courageous, Energetic",
    size: "Medium",
    lifespan: "10–14 years",
    referencePhotoUrl: null,
  },
  {
    id: "bernese-mountain-dog",
    name: "Bernese Mountain Dog",
    rarity: "rare",
    points: RARITY_POINTS.rare,
    subtitle: "Gentle giant mountain dog known for strength and loyalty.",
    description:
      "Bernese Mountain Dogs are powerful working dogs originally bred for farm work in the Swiss Alps. They are affectionate family companions that thrive in cooler climates.",
    origin: "Switzerland",
    temperament: "Gentle, Loyal, Calm",
    size: "Large",
    lifespan: "7–10 years",
    referencePhotoUrl: null,
  },
  {
    id: "rhodesian-ridgeback",
    name: "Rhodesian Ridgeback",
    rarity: "rare",
    points: RARITY_POINTS.rare,
    subtitle: "Athletic African hunting dog known for independence and endurance.",
    description:
      "Rhodesian Ridgebacks are muscular dogs bred for hunting and guarding in southern Africa. They are calm, protective companions with impressive stamina.",
    origin: "Zimbabwe",
    temperament: "Confident, Loyal, Independent",
    size: "Large",
    lifespan: "10–12 years",
    referencePhotoUrl: null,
  },
  {
    id: "weimaraner",
    name: "Weimaraner",
    rarity: "rare",
    points: RARITY_POINTS.rare,
    subtitle: "Elegant sporting dog recognised for its silver-grey coat.",
    description:
      "Weimaraners are athletic hunting dogs known for speed, endurance, and strong bonds with owners. They require lots of exercise and mental stimulation.",
    origin: "Germany",
    temperament: "Energetic, Intelligent, Affectionate",
    size: "Large",
    lifespan: "11–13 years",
    referencePhotoUrl: null,
  },
  {
    id: "dobermann",
    name: "Dobermann",
    rarity: "rare",
    points: RARITY_POINTS.rare,
    subtitle: "Powerful and intelligent guardian dog with unmatched loyalty.",
    description:
      "Dobermanns are athletic working dogs bred for protection and companionship. They are highly trainable and excel in obedience, guarding, and police work.",
    origin: "Germany",
    temperament: "Fearless, Loyal, Intelligent",
    size: "Large",
    lifespan: "10–13 years",
    referencePhotoUrl: null,
  },
  {
    id: "great-dane",
    name: "Great Dane",
    rarity: "rare",
    points: RARITY_POINTS.rare,
    subtitle: "Massive yet gentle companion known for its calm temperament.",
    description:
      "Great Danes are towering dogs originally bred for hunting large game. Despite their size, they are affectionate family companions often called gentle giants.",
    origin: "Germany",
    temperament: "Friendly, Gentle, Courageous",
    size: "Giant",
    lifespan: "7–10 years",
    referencePhotoUrl: null,
  },
  {
    id: "german-shorthaired-pointer",
    name: "German Shorthaired Pointer",
    rarity: "rare",
    points: RARITY_POINTS.rare,
    subtitle: "Versatile sporting dog built for speed, stamina, and hunting.",
    description:
      "German Shorthaired Pointers are highly athletic hunting dogs that excel on land and in water. They thrive in active households and love outdoor adventure.",
    origin: "Germany",
    temperament: "Energetic, Intelligent, Friendly",
    size: "Large",
    lifespan: "12–14 years",
    referencePhotoUrl: null,
  },
  {
    id: "samoyed",
    name: "Samoyed",
    rarity: "rare",
    points: RARITY_POINTS.rare,
    subtitle: "Fluffy Arctic working dog famous for its smiling expression.",
    description:
      "Samoyeds are hardy sled dogs bred to work in freezing Arctic climates. They are affectionate companions with thick white coats and playful personalities.",
    origin: "Russia",
    temperament: "Friendly, Gentle, Social",
    size: "Large",
    lifespan: "12–14 years",
    referencePhotoUrl: null,
  },
  {
    id: "pembroke-welsh-corgi",
    name: "Pembroke Welsh Corgi",
    rarity: "rare",
    points: RARITY_POINTS.rare,
    subtitle: "Small herding dog with a bold personality and short legs.",
    description:
      "Pembroke Welsh Corgis are energetic herding dogs known for their fox-like faces and long bodies. They are affectionate companions with strong working instincts.",
    origin: "Wales",
    temperament: "Playful, Intelligent, Alert",
    size: "Small",
    lifespan: "12–15 years",
    referencePhotoUrl: null,
  },
  {
    id: "greyhound",
    name: "Greyhound",
    rarity: "rare",
    points: RARITY_POINTS.rare,
    subtitle: "Elegant racing dog built for incredible speed and grace.",
    description:
      "Greyhounds are sleek sighthounds bred for chasing prey and racing. Despite their speed, they are calm indoor companions that enjoy relaxing.",
    origin: "United Kingdom",
    temperament: "Gentle, Quiet, Athletic",
    size: "Large",
    lifespan: "10–14 years",
    referencePhotoUrl: null,
  },
  {
    id: "basset-hound",
    name: "Basset Hound",
    rarity: "rare",
    points: RARITY_POINTS.rare,
    subtitle: "Low-slung scent hound famous for its nose and droopy ears.",
    description:
      "Basset Hounds are scent-tracking dogs with incredible noses and laid-back personalities. They are affectionate companions that enjoy following scents wherever they lead.",
    origin: "France",
    temperament: "Gentle, Relaxed, Stubborn",
    size: "Medium",
    lifespan: "10–12 years",
    referencePhotoUrl: null,
  },
  {
    id: "vizsla",
    name: "Vizsla",
    rarity: "rare",
    points: RARITY_POINTS.rare,
    subtitle: "Elegant Hungarian sporting dog known for affection and athleticism.",
    description:
      "Vizslas are highly athletic hunting dogs that form close bonds with their owners. They are energetic companions that thrive on exercise and attention.",
    origin: "Hungary",
    temperament: "Affectionate, Energetic, Gentle",
    size: "Large",
    lifespan: "12–15 years",
    referencePhotoUrl: null,
  },
  {
    id: "cane-corso",
    name: "Cane Corso",
    rarity: "rare",
    points: RARITY_POINTS.rare,
    subtitle: "Large Italian guardian dog with strength and confidence.",
    description:
      "Cane Corsos are powerful mastiff-type dogs bred for guarding and protection. They are calm, confident companions that require strong training and leadership.",
    origin: "Italy",
    temperament: "Protective, Intelligent, Loyal",
    size: "Large",
    lifespan: "9–12 years",
    referencePhotoUrl: null,
  },
  {
    id: "irish-wolfhound",
    name: "Irish Wolfhound",
    rarity: "legendary",
    points: RARITY_POINTS.legendary,
    subtitle: "Towering sighthound known for calmness and historic hunting ability.",
    description:
      "Irish Wolfhounds are enormous yet gentle dogs originally bred for hunting wolves and large game. They are affectionate companions with relaxed personalities.",
    origin: "Ireland",
    temperament: "Gentle, Courageous, Calm",
    size: "Giant",
    lifespan: "6–8 years",
    referencePhotoUrl: null,
  },
  {
    id: "chow-chow",
    name: "Chow Chow",
    rarity: "legendary",
    points: RARITY_POINTS.legendary,
    subtitle: "Distinctive fluffy companion known for independence and dignity.",
    description:
      "Chow Chows are ancient dogs recognised for their lion-like mane and calm personality. They are loyal companions that tend to bond closely with family.",
    origin: "China",
    temperament: "Reserved, Loyal, Independent",
    size: "Medium–Large",
    lifespan: "9–15 years",
    referencePhotoUrl: null,
  },
  {
    id: "xoloitzcuintli",
    name: "Xoloitzcuintli",
    rarity: "legendary",
    points: RARITY_POINTS.legendary,
    subtitle: "Ancient Mexican breed valued for loyalty and unique appearance.",
    description:
      "Xoloitzcuintlis are one of the oldest dog breeds in the world and are known for their often hairless appearance. They are affectionate companions with calm temperaments.",
    origin: "Mexico",
    temperament: "Calm, Loyal, Intelligent",
    size: "Small–Medium",
    lifespan: "13–18 years",
    referencePhotoUrl: null,
  },
];

export const rarityOrder = ["common", "uncommon", "rare", "legendary"] as const;

/** Same order as Dogdex hex grids: rarity blocks in `rarityOrder`, then name A–Z within each (row-major in 3 columns). */
export function buildDogdexBreedOrder(breeds: Breed[]): Breed[] {
  const out: Breed[] = [];
  for (const rarity of rarityOrder) {
    out.push(...breeds.filter((b) => b.rarity === rarity).sort((a, b) => a.name.localeCompare(b.name)));
  }
  return out;
}
