import type { Breed, BreedRarity } from "@/types/app";

/** Base points per scan by rarity (featured multiplier applied in the store). */
export const RARITY_POINTS: Record<BreedRarity, number> = {
  common: 1,
  uncommon: 3,
  rare: 7,
  legendary: 15,
};

export const breedsCatalog: Breed[] = [
  { id: "cavoodle", name: "Cavoodle", rarity: "common", points: RARITY_POINTS.common, description: "A gentle companion mix prized for its affectionate nature.", origin: "Australia", temperament: "Friendly, playful, social", size: "Small", lifespan: "10-15 years", referencePhotoUrl: null },
  { id: "labrador-retriever", name: "Labrador Retriever", rarity: "common", points: RARITY_POINTS.common, description: "A famously reliable family dog with boundless enthusiasm.", origin: "Canada", temperament: "Outgoing, eager, kind", size: "Large", lifespan: "10-12 years", referencePhotoUrl: null },
  { id: "golden-retriever", name: "Golden Retriever", rarity: "common", points: RARITY_POINTS.common, description: "A sunny sporting dog known for patience and trainability.", origin: "Scotland", temperament: "Intelligent, friendly, devoted", size: "Large", lifespan: "10-12 years", referencePhotoUrl: null },
  { id: "french-bulldog", name: "French Bulldog", rarity: "common", points: RARITY_POINTS.common, description: "A compact city dog with a charming, clownish streak.", origin: "France", temperament: "Adaptable, alert, affectionate", size: "Small", lifespan: "10-12 years", referencePhotoUrl: null },
  { id: "german-shepherd", name: "German Shepherd", rarity: "common", points: RARITY_POINTS.common, description: "A confident working breed with strong loyalty and focus.", origin: "Germany", temperament: "Courageous, smart, devoted", size: "Large", lifespan: "9-13 years", referencePhotoUrl: null },
  { id: "border-collie", name: "Border Collie", rarity: "common", points: RARITY_POINTS.common, description: "An intensely clever herding dog that thrives on activity.", origin: "United Kingdom", temperament: "Energetic, focused, responsive", size: "Medium", lifespan: "12-15 years", referencePhotoUrl: null },
  { id: "staffordshire-bull-terrier", name: "Staffordshire Bull Terrier", rarity: "common", points: RARITY_POINTS.common, description: "A sturdy people-focused terrier with a big heart.", origin: "England", temperament: "Bold, affectionate, tenacious", size: "Medium", lifespan: "12-14 years", referencePhotoUrl: null },
  { id: "groodle", name: "Groodle", rarity: "common", points: RARITY_POINTS.common, description: "A social doodle mix combining friendliness with fluff.", origin: "Australia", temperament: "Sociable, cheerful, bright", size: "Large", lifespan: "10-14 years", referencePhotoUrl: null },
  { id: "miniature-dachshund", name: "Miniature Dachshund", rarity: "common", points: RARITY_POINTS.common, description: "A bold little hound with a long body and lots of attitude.", origin: "Germany", temperament: "Curious, brave, lively", size: "Small", lifespan: "12-16 years", referencePhotoUrl: null },
  { id: "cavalier-king-charles-spaniel", name: "Cavalier King Charles Spaniel", rarity: "common", points: RARITY_POINTS.common, description: "A sweet lap dog that loves company and comfort.", origin: "United Kingdom", temperament: "Gentle, graceful, affectionate", size: "Small", lifespan: "9-14 years", referencePhotoUrl: null },
  { id: "labradoodle", name: "Labradoodle", rarity: "common", points: RARITY_POINTS.common, description: "A popular doodle mix with a playful, family-friendly vibe.", origin: "Australia", temperament: "Friendly, active, intuitive", size: "Medium", lifespan: "12-15 years", referencePhotoUrl: null },
  { id: "poodle-miniature", name: "Poodle (Miniature)", rarity: "common", points: RARITY_POINTS.common, description: "A compact, highly trainable dog with a lively personality.", origin: "France", temperament: "Smart, agile, alert", size: "Small", lifespan: "10-18 years", referencePhotoUrl: null },
  { id: "maltese", name: "Maltese", rarity: "common", points: RARITY_POINTS.common, description: "A bright toy breed with a silky coat and fearless spirit.", origin: "Malta", temperament: "Playful, affectionate, lively", size: "Small", lifespan: "12-15 years", referencePhotoUrl: null },
  { id: "jack-russell-terrier", name: "Jack Russell Terrier", rarity: "common", points: RARITY_POINTS.common, description: "A high-drive terrier packed with confidence and speed.", origin: "England", temperament: "Energetic, bold, clever", size: "Small", lifespan: "13-16 years", referencePhotoUrl: null },
  { id: "shih-tzu", name: "Shih Tzu", rarity: "common", points: RARITY_POINTS.common, description: "A cheerful companion bred for close human company.", origin: "China", temperament: "Outgoing, affectionate, calm", size: "Small", lifespan: "10-16 years", referencePhotoUrl: null },
  { id: "cocker-spaniel", name: "Cocker Spaniel", rarity: "uncommon", points: RARITY_POINTS.uncommon, description: "A merry sporting breed with expressive eyes and soft ears.", origin: "United Kingdom", temperament: "Gentle, merry, adaptable", size: "Medium", lifespan: "12-15 years", referencePhotoUrl: null },
  { id: "beagle", name: "Beagle", rarity: "uncommon", points: RARITY_POINTS.uncommon, description: "A scent hound that follows its nose with joyful stubbornness.", origin: "England", temperament: "Curious, merry, determined", size: "Medium", lifespan: "12-15 years", referencePhotoUrl: null },
  { id: "miniature-schnauzer", name: "Miniature Schnauzer", rarity: "uncommon", points: RARITY_POINTS.uncommon, description: "A spirited small dog known for its beard and confidence.", origin: "Germany", temperament: "Friendly, alert, trainable", size: "Small", lifespan: "12-15 years", referencePhotoUrl: null },
  { id: "spoodle", name: "Spoodle", rarity: "uncommon", points: RARITY_POINTS.uncommon, description: "A spaniel-poodle mix that tends to be clever and cuddly.", origin: "Australia", temperament: "Happy, social, adaptable", size: "Small", lifespan: "12-15 years", referencePhotoUrl: null },
  { id: "australian-shepherd", name: "Australian Shepherd", rarity: "uncommon", points: RARITY_POINTS.uncommon, description: "A hard-working herding breed with striking energy and focus.", origin: "United States", temperament: "Smart, active, loyal", size: "Medium", lifespan: "12-15 years", referencePhotoUrl: null },
  { id: "pug", name: "Pug", rarity: "uncommon", points: RARITY_POINTS.uncommon, description: "A comic companion with a compact build and huge personality.", origin: "China", temperament: "Charming, loving, mischievous", size: "Small", lifespan: "12-15 years", referencePhotoUrl: null },
  { id: "chihuahua", name: "Chihuahua", rarity: "uncommon", points: RARITY_POINTS.uncommon, description: "A tiny dog with alert ears and outsized confidence.", origin: "Mexico", temperament: "Lively, devoted, bold", size: "Small", lifespan: "14-16 years", referencePhotoUrl: null },
  { id: "bichon-frise", name: "Bichon Frise", rarity: "uncommon", points: RARITY_POINTS.uncommon, description: "A cheerful white companion dog with a soft curly coat.", origin: "Mediterranean", temperament: "Playful, affectionate, bright", size: "Small", lifespan: "14-15 years", referencePhotoUrl: null },
  { id: "boxer", name: "Boxer", rarity: "uncommon", points: RARITY_POINTS.uncommon, description: "A muscular, bouncy breed that stays puppyish for years.", origin: "Germany", temperament: "Fun-loving, loyal, energetic", size: "Large", lifespan: "10-12 years", referencePhotoUrl: null },
  { id: "rottweiler", name: "Rottweiler", rarity: "uncommon", points: RARITY_POINTS.uncommon, description: "A robust guardian with a calm center and strong devotion.", origin: "Germany", temperament: "Confident, steady, protective", size: "Large", lifespan: "9-10 years", referencePhotoUrl: null },
  { id: "siberian-husky", name: "Siberian Husky", rarity: "uncommon", points: RARITY_POINTS.uncommon, description: "A striking sled dog built for endurance and adventure.", origin: "Siberia", temperament: "Outgoing, mischievous, athletic", size: "Medium", lifespan: "12-14 years", referencePhotoUrl: null },
  { id: "whippet", name: "Whippet", rarity: "uncommon", points: RARITY_POINTS.uncommon, description: "A sleek sprinter that is gentle and calm at home.", origin: "England", temperament: "Calm, affectionate, fast", size: "Medium", lifespan: "12-15 years", referencePhotoUrl: null },
  { id: "west-highland-white-terrier", name: "West Highland White Terrier", rarity: "uncommon", points: RARITY_POINTS.uncommon, description: "A sturdy white terrier with confidence and charm.", origin: "Scotland", temperament: "Alert, cheerful, spirited", size: "Small", lifespan: "13-15 years", referencePhotoUrl: null },
  { id: "australian-cattle-dog", name: "Australian Cattle Dog", rarity: "uncommon", points: RARITY_POINTS.uncommon, description: "A rugged herding dog bred for stamina and grit.", origin: "Australia", temperament: "Alert, tough, loyal", size: "Medium", lifespan: "12-16 years", referencePhotoUrl: null },
  { id: "kelpie", name: "Kelpie", rarity: "uncommon", points: RARITY_POINTS.uncommon, description: "An agile Australian worker that thrives on jobs to do.", origin: "Australia", temperament: "Driven, alert, intelligent", size: "Medium", lifespan: "11-16 years", referencePhotoUrl: null },
  { id: "dalmatian", name: "Dalmatian", rarity: "uncommon", points: RARITY_POINTS.uncommon, description: "A spotted endurance dog with athletic flair.", origin: "Croatia", temperament: "Energetic, poised, outgoing", size: "Large", lifespan: "11-13 years", referencePhotoUrl: null },
  { id: "shiba-inu", name: "Shiba Inu", rarity: "uncommon", points: RARITY_POINTS.uncommon, description: "A fox-like Japanese spitz with independence and composure.", origin: "Japan", temperament: "Bold, clean, alert", size: "Small", lifespan: "13-16 years", referencePhotoUrl: null },
  { id: "pomeranian", name: "Pomeranian", rarity: "uncommon", points: RARITY_POINTS.uncommon, description: "A fluffy toy dog that carries itself with confidence.", origin: "Germany/Poland", temperament: "Bold, lively, curious", size: "Small", lifespan: "12-16 years", referencePhotoUrl: null },
  { id: "yorkshire-terrier", name: "Yorkshire Terrier", rarity: "uncommon", points: RARITY_POINTS.uncommon, description: "A glamorous small terrier with a fearless streak.", origin: "England", temperament: "Affectionate, spirited, brave", size: "Small", lifespan: "11-15 years", referencePhotoUrl: null },
  { id: "bull-terrier", name: "Bull Terrier", rarity: "uncommon", points: RARITY_POINTS.uncommon, description: "A distinctive egg-headed terrier with playful determination.", origin: "England", temperament: "Mischievous, loyal, energetic", size: "Medium", lifespan: "12-13 years", referencePhotoUrl: null },
  { id: "bernese-mountain-dog", name: "Bernese Mountain Dog", rarity: "rare", points: RARITY_POINTS.rare, description: "A giant mountain breed known for warmth and calm power.", origin: "Switzerland", temperament: "Calm, affectionate, strong", size: "Large", lifespan: "7-10 years", referencePhotoUrl: null },
  { id: "rhodesian-ridgeback", name: "Rhodesian Ridgeback", rarity: "rare", points: RARITY_POINTS.rare, description: "A dignified hound with athletic grace and independence.", origin: "Southern Africa", temperament: "Loyal, strong-willed, calm", size: "Large", lifespan: "10-12 years", referencePhotoUrl: null },
  { id: "weimaraner", name: "Weimaraner", rarity: "rare", points: RARITY_POINTS.rare, description: "A sleek silver sporting dog built for stamina and speed.", origin: "Germany", temperament: "Energetic, fearless, bright", size: "Large", lifespan: "10-13 years", referencePhotoUrl: null },
  { id: "dobermann", name: "Dobermann", rarity: "rare", points: RARITY_POINTS.rare, description: "A powerful protector with elegance and precision.", origin: "Germany", temperament: "Alert, loyal, fearless", size: "Large", lifespan: "10-12 years", referencePhotoUrl: null },
  { id: "great-dane", name: "Great Dane", rarity: "rare", points: RARITY_POINTS.rare, description: "A towering gentle giant with a surprisingly sweet demeanor.", origin: "Germany", temperament: "Friendly, dependable, patient", size: "Giant", lifespan: "7-10 years", referencePhotoUrl: null },
  { id: "german-shorthaired-pointer", name: "German Shorthaired Pointer", rarity: "rare", points: RARITY_POINTS.rare, description: "A versatile sporting dog with drive and intelligence.", origin: "Germany", temperament: "Active, eager, smart", size: "Large", lifespan: "10-14 years", referencePhotoUrl: null },
  { id: "samoyed", name: "Samoyed", rarity: "rare", points: RARITY_POINTS.rare, description: "A smiling spitz breed with a thick white coat.", origin: "Siberia", temperament: "Friendly, gentle, adaptable", size: "Large", lifespan: "12-14 years", referencePhotoUrl: null },
  { id: "pembroke-welsh-corgi", name: "Pembroke Welsh Corgi", rarity: "rare", points: RARITY_POINTS.rare, description: "A low-set herding dog with keen intelligence and charm.", origin: "Wales", temperament: "Bold, outgoing, bright", size: "Small", lifespan: "12-13 years", referencePhotoUrl: null },
  { id: "greyhound", name: "Greyhound", rarity: "rare", points: RARITY_POINTS.rare, description: "A noble sighthound that balances speed with serenity.", origin: "Egypt/United Kingdom", temperament: "Gentle, quiet, athletic", size: "Large", lifespan: "10-14 years", referencePhotoUrl: null },
  { id: "basset-hound", name: "Basset Hound", rarity: "rare", points: RARITY_POINTS.rare, description: "A low scent hound with droopy features and patient charm.", origin: "France", temperament: "Laid-back, loyal, stubborn", size: "Medium", lifespan: "10-12 years", referencePhotoUrl: null },
  { id: "vizsla", name: "Vizsla", rarity: "rare", points: RARITY_POINTS.rare, description: "A velcro sporting dog that thrives on close companionship.", origin: "Hungary", temperament: "Affectionate, energetic, gentle", size: "Large", lifespan: "12-14 years", referencePhotoUrl: null },
  { id: "cane-corso", name: "Cane Corso", rarity: "rare", points: RARITY_POINTS.rare, description: "A strong mastiff with protective instincts and composure.", origin: "Italy", temperament: "Reserved, confident, loyal", size: "Large", lifespan: "9-12 years", referencePhotoUrl: null },
  { id: "irish-wolfhound", name: "Irish Wolfhound", rarity: "legendary", points: RARITY_POINTS.legendary, description: "A colossal sighthound with quiet dignity and gentleness.", origin: "Ireland", temperament: "Patient, generous, calm", size: "Giant", lifespan: "6-8 years", referencePhotoUrl: null },
  { id: "chow-chow", name: "Chow Chow", rarity: "legendary", points: RARITY_POINTS.legendary, description: "A lion-like spitz with a proud and independent nature.", origin: "China", temperament: "Reserved, dignified, loyal", size: "Medium", lifespan: "8-12 years", referencePhotoUrl: null },
  { id: "xoloitzcuintli", name: "Xoloitzcuintli", rarity: "legendary", points: RARITY_POINTS.legendary, description: "An ancient Mexican breed often seen with little or no coat.", origin: "Mexico", temperament: "Calm, attentive, loyal", size: "Medium", lifespan: "13-18 years", referencePhotoUrl: null },
];

export const rarityOrder = ["common", "uncommon", "rare", "legendary"] as const;

/** Same order as Dogdex hex grids: rarity blocks in `rarityOrder`, then name A–Z within each (row-major in 3 columns). */
export function buildDogdexBreedOrder(breeds: Breed[]): Breed[] {
  const out: Breed[] = [];
  for (const rarity of rarityOrder) {
    out.push(...breeds.filter((b) => b.rarity === rarity).sort((a, b) => a.name.localeCompare(b.name)));
  }
  return out;
}
