/**
 * Per-breed crops on assets/common-dogs.png — regenerated by scripts/sync-sprite-crops.mjs
 *
 * Dogdex hex, BreedSpriteThumb, FeaturedTodayCard, and BreedMiniIcon use line-art PNGs first when
 * defined in `src/lib/breedLineArtSprite.ts` (cavoodle, groodle, labradoodle, cavalier). For those
 * breeds, edits here have no visible effect until you remove them from line-art or change the crop
 * in `breedLineArtSprite.ts`.
 */
export const COMMON_SPRITE_SIZE = { w: 1024, h: 1024 } as const;

export const commonBreedCrops: Record<
  string,
  { x: number; y: number; w: number; h: number; feetY: number; dx?: number; dy?: number; scale?: number }
> = {
  /** Sheet-only; hex UI uses `breed-line-art/cavoodle.png` — tune crop in `breedLineArtSprite.ts`. */
  cavoodle: { x: 54, y: 78, w: 140, h: 81, feetY: 158 },
  "labrador-retriever": { x: 284, y: 73, w: 202, h: 86, feetY: 158 },
  "golden-retriever": { x: 516, y: 69, w: 222, h: 90, feetY: 158 },
  "french-bulldog": { x: 808, y: 82, w: 142, h: 77, feetY: 158 },
  "german-shepherd": { x: 51, y: 256, w: 182, h: 159, feetY: 414 },
  "border-collie": { x: 276, y: 256, w: 199, h: 159, feetY: 414 },
  "staffordshire-bull-terrier": { x: 534, y: 256, w: 188, h: 159, feetY: 414 },
  groodle: { x: 778, y: 256, w: 187, h: 159, feetY: 414 },
  "miniature-dachshund": { x: 35, y: 574, w: 191, h: 97, feetY: 670 },
  /** Wider + taller than auto-bbox so the tail and hind leg stay in frame (grid cell x256–512). */
  "cavalier-king-charles-spaniel": { x: 250, y: 550, w: 248, h: 121, feetY: 670 },
  labradoodle: { x: 528, y: 541, w: 192, h: 130, feetY: 670 },
  "poodle-miniature": { x: 780, y: 536, w: 153, h: 135, feetY: 670 },
  maltese: { x: 76, y: 793, w: 159, h: 134, feetY: 926 },
  "jack-russell-terrier": { x: 315, y: 797, w: 167, h: 130, feetY: 926 },
  "shih-tzu": { x: 551, y: 799, w: 158, h: 128, feetY: 926 },
};
