/**
 * Per-breed crops on assets/rare-legendary-dogs.png — regenerated by scripts/sync-sprite-crops.mjs
 * Grid: 6 columns × 3 rows (last row: three breeds). Run make-rare-legendary-transparent first if needed.
 */
export const RARE_LEGENDARY_SPRITE_SIZE = { w: 1024, h: 682 } as const;

export const rareLegendaryBreedCrops: Record<
  string,
  { x: number; y: number; w: number; h: number; feetY: number; dx?: number; dy?: number; scale?: number }
> = {
  "bernese-mountain-dog": { x: 23, y: 38, w: 148, h: 103, feetY: 140 },
  "rhodesian-ridgeback": { x: 171, y: 39, w: 170, h: 102, feetY: 140 },
  weimaraner: { x: 341, y: 42, w: 171, h: 99, feetY: 140 },
  dobermann: { x: 512, y: 31, w: 150, h: 139, feetY: 140 },
  "great-dane": { x: 683, y: 26, w: 169, h: 115, feetY: 140 },
  "german-shorthaired-pointer": { x: 872, y: 63, w: 149, h: 78, feetY: 140 },
  samoyed: { x: 24, y: 238, w: 147, h: 130, feetY: 367 },
  "pembroke-welsh-corgi": { x: 199, y: 272, w: 142, h: 96, feetY: 367 },
  greyhound: { x: 353, y: 248, w: 159, h: 120, feetY: 367 },
  "basset-hound": { x: 512, y: 262, w: 171, h: 106, feetY: 367 },
  vizsla: { x: 704, y: 255, w: 146, h: 113, feetY: 367 },
  "cane-corso": { x: 854, y: 240, w: 153, h: 128, feetY: 367 },
  "irish-wolfhound": { x: 189, y: 454, w: 184, h: 174, feetY: 627 },
  "chow-chow": { x: 430, y: 479, w: 141, h: 150, feetY: 628 },
  xoloitzcuintli: { x: 609, y: 467, w: 137, h: 161, feetY: 627 },
};
