/**
 * Per-breed crops on assets/uncommon-dogs.png — regenerated by scripts/sync-sprite-crops.mjs
 */
export const UNCOMMON_SPRITE_SIZE = { w: 1024, h: 1024 } as const;

export const uncommonBreedCrops: Record<
  string,
  { x: number; y: number; w: number; h: number; feetY: number; dx?: number; dy?: number; scale?: number }
> = {
  "cocker-spaniel": { x: 48, y: 73, w: 157, h: 86, feetY: 158 },
  beagle: { x: 247, y: 99, w: 159, h: 60, feetY: 158 },
  "miniature-schnauzer": { x: 442, y: 76, w: 155, h: 83, feetY: 158 },
  spoodle: { x: 635, y: 74, w: 151, h: 85, feetY: 158 },
  "australian-shepherd": { x: 827, y: 80, w: 165, h: 79, feetY: 158 },
  pug: { x: 35, y: 256, w: 162, h: 159, feetY: 414 },
  chihuahua: { x: 242, y: 256, w: 139, h: 159, feetY: 414 },
  "bichon-frise": { x: 410, y: 256, w: 204, h: 159, feetY: 414 },
  boxer: { x: 625, y: 256, w: 194, h: 159, feetY: 414 },
  rottweiler: { x: 819, y: 256, w: 185, h: 159, feetY: 414 },
  "siberian-husky": { x: 35, y: 512, w: 170, h: 159, feetY: 670 },
  whippet: { x: 205, y: 529, w: 205, h: 142, feetY: 670 },
  "west-highland-white-terrier": { x: 439, y: 550, w: 158, h: 121, feetY: 670 },
  "australian-cattle-dog": { x: 616, y: 518, w: 203, h: 153, feetY: 670 },
  kelpie: { x: 819, y: 525, w: 163, h: 146, feetY: 670 },
  dalmatian: { x: 26, y: 768, w: 179, h: 159, feetY: 922 },
  "shiba-inu": { x: 205, y: 769, w: 188, h: 158, feetY: 922 },
  pomeranian: { x: 428, y: 782, w: 155, h: 140, feetY: 922 },
  "yorkshire-terrier": { x: 623, y: 778, w: 196, h: 149, feetY: 922 },
  "bull-terrier": { x: 819, y: 769, w: 159, h: 158, feetY: 922 },
};
